using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CashierApplication
{
    public class Item
    {
        protected string item_name;
        protected double item_price;
        protected int item_quantity;
        protected double total_price;

        public Item(string name, double price, int quantity)
        {
            this.item_name = name;
            this.item_price = price;
            this.item_quantity = quantity;
        }

        public virtual double getTotalPrice()
        {
            this.total_price = this.item_price * this.item_quantity;
            return this.total_price;
        }

        public void setPayment(double amount)
        {
        }
    }
}
